/*
 * Created on 13 Aug 2016 ( Time 12:34:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.app.common.dao.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "group_type"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="group_type")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="GroupTypeEntity.countAll", query="SELECT COUNT(x) FROM GroupTypeEntity x" )
} )
public class GroupTypeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="type_id", nullable=false)
    private Integer    typeId       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="group_code", nullable=false, length=50)
    private String     groupCode    ;

    @Column(name="group_type_name", nullable=false, length=50)
    private String     groupTypeName ;

    @Column(name="group_description", nullable=false, length=500)
    private String     groupDescription ;

    @Column(name="group_pics", length=1000)
    private String     groupPics    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public GroupTypeEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setTypeId( Integer typeId ) {
        this.typeId = typeId ;
    }
    public Integer getTypeId() {
        return this.typeId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : group_code ( VARCHAR ) 
    public void setGroupCode( String groupCode ) {
        this.groupCode = groupCode;
    }
    public String getGroupCode() {
        return this.groupCode;
    }

    //--- DATABASE MAPPING : group_type_name ( VARCHAR ) 
    public void setGroupTypeName( String groupTypeName ) {
        this.groupTypeName = groupTypeName;
    }
    public String getGroupTypeName() {
        return this.groupTypeName;
    }

    //--- DATABASE MAPPING : group_description ( VARCHAR ) 
    public void setGroupDescription( String groupDescription ) {
        this.groupDescription = groupDescription;
    }
    public String getGroupDescription() {
        return this.groupDescription;
    }

    //--- DATABASE MAPPING : group_pics ( VARCHAR ) 
    public void setGroupPics( String groupPics ) {
        this.groupPics = groupPics;
    }
    public String getGroupPics() {
        return this.groupPics;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(typeId);
        sb.append("]:"); 
        sb.append(groupCode);
        sb.append("|");
        sb.append(groupTypeName);
        sb.append("|");
        sb.append(groupDescription);
        sb.append("|");
        sb.append(groupPics);
        return sb.toString(); 
    } 

}
